# Generated by Django 5.0.2 on 2025-12-03 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Tél vérifié ?')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('photo', models.ImageField(upload_to='tutors/photos/', verbose_name='Photo Profil')),
                ('cni_document', models.FileField(blank=True, upload_to='secure/identity/', verbose_name='CNI / Passeport')),
                ('casier_judiciaire', models.FileField(blank=True, upload_to='secure/legal/', verbose_name='Casier Judiciaire')),
                ('diplomes_file', models.FileField(blank=True, upload_to='secure/diplomas/', verbose_name='Diplômes')),
                ('status', models.CharField(choices=[('draft', 'Brouillon - Incomplet'), ('pending', 'En attente de validation'), ('validated', 'Validé - Visible'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut Dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
