# Generated by Django 5.0.2 on 2025-12-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_home_class',
            field=models.BooleanField(default=True, verbose_name='Accepte les cours à domicile ?'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_online_class',
            field=models.BooleanField(default=False, verbose_name='Accepte les cours en ligne ?'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='education.level', verbose_name='Niveaux acceptés'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='education.subject', verbose_name='Matières enseignées'),
        ),
    ]
