# Generated by Django 5.0.2 on 2025-12-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tutorprofile_is_home_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Raison du rejet ou commentaires internes', verbose_name='Note Admin'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse (Quartier/Ville)'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Téléphone vérifié ?'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='bio',
            field=models.TextField(help_text='Présentez-vous aux parents.', verbose_name='Biographie / Motivation'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='diplomes_file',
            field=models.FileField(blank=True, upload_to='secure/diplomas/', verbose_name='Diplômes (PDF)'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='photo',
            field=models.ImageField(upload_to='tutors/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon - Incomplet'), ('pending', 'En attente de validation'), ('validated', 'Validé - Visible'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='draft', max_length=20, verbose_name='Statut du dossier'),
        ),
    ]
