# Generated by Django 5.0.2 on 2025-12-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('education', '0001_initial'),
        ('profiles', '0003_tutorprofile_admin_notes_tutorprofile_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Ville de résidence'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier / Commune'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Note Admin'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='bio',
            field=models.TextField(help_text='Présentez-vous aux parents.', verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='diplomes_file',
            field=models.FileField(blank=True, upload_to='secure/diplomas/', verbose_name='Diplômes'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='is_home_class',
            field=models.BooleanField(default=True, verbose_name='Accepte cours à domicile'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='is_online_class',
            field=models.BooleanField(default=False, verbose_name='Accepte cours en ligne'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='education.level', verbose_name='Niveaux'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon - Incomplet'), ('pending', 'En attente de validation'), ('validated', 'Validé - Visible'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='education.subject', verbose_name='Matières'),
        ),
    ]
