# Generated by Django 5.0.2 on 2025-12-03 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_tutorprofile_admin_notes_tutorprofile_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(verbose_name='Montant payé (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_contacts', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='profiles.tutorprofile')),
            ],
            options={
                'verbose_name': 'Déblocage Contact',
                'verbose_name_plural': 'Déblocages Contacts',
                'unique_together': {('parent_user', 'tutor_profile')},
            },
        ),
    ]
