# Generated by Django 5.0.2 on 2025-12-03 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier précis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Fréquence (ex: 2x par semaine)')),
                ('is_online', models.BooleanField(default=False, verbose_name='Accepte les cours en ligne')),
                ('budget_range', models.CharField(choices=[('low', 'Moins de 20.000 FCFA'), ('medium', '20.000 - 30.000 FCFA'), ('standard', '30.000 - 50.000 FCFA'), ('high', '50.000 - 80.000 FCFA'), ('premium', 'Plus de 80.000 FCFA')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Détails du besoin')),
                ('status', models.CharField(choices=[('active', 'Recherche en cours'), ('consulting', 'En discussion'), ('closed', 'Professeur trouvé'), ('expired', 'Expirée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Ville')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.level', verbose_name="Niveau de l'élève")),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='education.subject', verbose_name='Matières souhaitées')),
            ],
        ),
    ]
