# Generated by Django 5.0.2 on 2025-12-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de cours', 'verbose_name_plural': 'Demandes de cours'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avis & Notation', 'verbose_name_plural': 'Avis & Notations'},
        ),
        migrations.AddField(
            model_name='courserequest',
            name='intention',
            field=models.CharField(choices=[('start', 'Je veux démarrer des cours'), ('info', 'Je souhaite seulement des informations')], default='start', max_length=10, verbose_name='Intention actuelle'),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qualification du Lead'),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='start_time',
            field=models.CharField(choices=[('asap', 'Dès que possible (dans les 7 jours)'), ('1-4weeks', 'Dans 1 à 4 semaines'), ('later', 'Plus tard / Je ne sais pas encore')], default='asap', max_length=20, verbose_name='Délai de démarrage'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='budget_range',
            field=models.CharField(choices=[('low', 'Moins de 20 000 F CFA'), ('medium_low', '20 000 - 30 000 F CFA'), ('standard', '30 000 - 50 000 F CFA'), ('high', '50 000 - 80 000 F CFA'), ('premium', 'Plus de 80 000 F CFA')], default='standard', max_length=20, verbose_name='Budget mensuel'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Détails supplémentaires'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Accepte les cours en ligne (Visio)'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(choices=[('active', 'Recherche en cours'), ('consulting', 'En discussion'), ('closed', 'Conclue / Prof trouvé'), ('expired', 'Expirée'), ('abandoned', 'Abandonnée')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'avis"),
        ),
    ]
