# Generated by Django 5.0.2 on 2025-12-03 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pays')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO (ex: CI)')),
                ('currency_symbol', models.CharField(default='F CFA', max_length=10, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif sur le site ?')),
                ('min_budget_threshold', models.IntegerField(default=30000, verbose_name='Seuil Budget Min (Scoring)')),
                ('subscription_price', models.IntegerField(default=3000, verbose_name='Prix Abonnement Prof')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Quartier/Commune')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='core.city')),
            ],
        ),
    ]
