# Generated by Django 5.0.2 on 2025-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Configuration Pays', 'verbose_name_plural': 'Configurations Pays'},
        ),
        migrations.AddField(
            model_name='country',
            name='casier_delay_weeks',
            field=models.IntegerField(default=4, verbose_name='Délai Casier (Semaines)'),
        ),
        migrations.AddField(
            model_name='country',
            name='contact_prices',
            field=models.CharField(default='1500,2000,3500,5000,10000', help_text='Prix des contacts (Primaire, Collège, Lycée, Exam, Premium)', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='relance_days',
            field=models.CharField(default='3,7,10', help_text='Jours de relance (ex: 3,7,10)', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Code ISO'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif ?'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='country',
            name='subscription_price',
            field=models.IntegerField(default=3000, verbose_name='Prix Abo Prof (30j)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Quartier',
        ),
    ]
